# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16GjFfr1U4_T_GCu0dAI4sMBJWpsVWoC6
"""

from flask import Flask,request
import slack
import json


app = Flask('app')
@app.route('/command', methods = ['POST'])
def command():
  client = slack.WebClient(token="xoxb-270567286518-4843879368611-sXuSzb7RLmEpmR3mcIUIDeeW")
  client.chat_postMessage(channel='U03T7BH7SPK', text= "certo")


if __name__ == '__main__':
  app.run(host='0.0.0.0', port=1300)